# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  desc "Upload a new build to TestFlight"
  lane :deploy do
    sh "flutter clean && flutter pub get"
    sh "rm -f Podfile.lock && pod install"
    sh "flutter build ipa --release"
    app_store_connect_api_key(
      key_id: "AB483SC484",
      issuer_id: "ed91d643-bec4-4821-9a7a-3cc9d63ba124",
      key_filepath: "fastlane/AB483SC484.p8"
    )
    upload_to_testflight(
      ipa: "../build/ios/ipa/notes_app.ipa",
      app_identifier: "com.andre.notesApp",
    )
  end
end

